apiVersion: v1
kind: Pod
metadata:
  labels:
    app: frontend
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
      resources: {}
  restartPolicy: Always
status: {}
